spotandjake theming update 1
repl-it-discord/repl-it-electron pull request #124
Opened 2021-02-07 02:44 UTC by spotandjake

Theming update gen 1 to simplify reflux addition as part 2 and remove ejs.

2021-02-07 22:25 UTC, CoolCoderSJ approved these changes
looks good but will mats themes still work or are we moving to reflux only?

2021-02-07 22:59 UTC, leon332157 commented
There should be an implementation we either convert mat's theme into a reflux theme or still include the older theme system.

2021-02-07 23:00 UTC, spotandjake commented
> There should be an implementation we either convert mat's theme into a reflux theme or still include the older theme system.

This is just temporary until we get reflux inmplemented to remove ejs and stuff, along with making relux integration easier.

2021-02-08 00:01 UTC, leon332157 requested changes
Change for variable naming and typing.

2021-02-08 00:01 UTC, leon332157 commented on src/app/themeHandler/themeHandler.ts
> +        this.Set(parentWindow, Themes[Name]);
Please change to camelCase or PascalCase and also fix the typing in function parameter. Use ElectronWindow for windows.

2021-02-08 00:08 UTC, spotandjake commented on src/app/themeHandler/themeHandler.ts
> +        this.Set(parentWindow, Themes[Name]);
i had to use any for the typing because the past in could be either a electron window or a browser window and i wanted to allow it to be both and i do not know exactly how to do that in ts also i will change that as well the the casing that is just a bad progrmamming habit lol. can we configure eslint for that

2021-02-08 02:30 UTC, leon332157 commented on src/app/themeHandler/themeHandler.ts
> +        this.Set(parentWindow, Themes[Name]);
Can you switch to ElectronWindow since I changed everything to use that

2021-02-08 04:29 UTC, leon332157 approved these changes

2021-02-08 04:42 UTC, merged